using Content.Client.Ember.Medical.PartStatus;
using Content.Shared.Ember.Medical.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.Ember.Medical.PartStatus.Widgets;

[GenerateTypedNameReferences]
public sealed partial class EmberPartStatusControl : UIWidget
{
    private readonly Dictionary<EmberTargetBodyPart, TextureRect> _partStatusControls;
    private readonly EmberPartStatusUIController _controller;
    public EmberPartStatusControl()
    {
        RobustXamlLoader.Load(this);

        _controller = UserInterfaceManager.GetUIController<EmberPartStatusUIController>();
        _partStatusControls = new Dictionary<EmberTargetBodyPart, TextureRect>
        {
            { EmberTargetBodyPart.Head, DollHead },
            { EmberTargetBodyPart.Torso, DollTorso },
            { EmberTargetBodyPart.Groin, DollGroin },
            { EmberTargetBodyPart.LeftArm, DollLeftArm },
            { EmberTargetBodyPart.LeftHand, DollLeftHand },
            { EmberTargetBodyPart.RightArm, DollRightArm },
            { EmberTargetBodyPart.RightHand, DollRightHand },
            { EmberTargetBodyPart.LeftLeg, DollLeftLeg },
            { EmberTargetBodyPart.LeftFoot, DollLeftFoot },
            { EmberTargetBodyPart.RightLeg, DollRightLeg },
            { EmberTargetBodyPart.RightFoot, DollRightFoot }
        };
    }

    public void SetTextures(Dictionary<EmberTargetBodyPart, EmberTargetIntegrity> state)
    {
        foreach (var (bodyPart, integrity) in state)
        {
            string enumName = Enum.GetName(typeof(EmberTargetBodyPart), bodyPart) ?? "Unknown";
            int enumValue = (int) integrity;
            var texture = new SpriteSpecifier.Rsi(new ResPath($"/Textures/Ember/Interface/Targeting/Status/{enumName.ToLowerInvariant()}.rsi"), $"{enumName.ToLowerInvariant()}_{enumValue}");
            _partStatusControls[bodyPart].Texture = _controller.GetTexture(texture);
        }
    }

    public void SetVisible(bool visible) => this.Visible = visible;

}
