using Content.Client.Ember.Construction;
using Content.Client.Decals.UI;
using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Content.Shared.SprayPainter;

namespace Content.Client.SprayPainter.UI;

[GenerateTypedNameReferences]
public sealed partial class SprayPainterWindow : DefaultWindow
{
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    private readonly EmberProceduralIconSystem _emberProceduralIcons;
    private readonly Texture _colorEntryTexture;
    private PaletteColorPicker? _palettePicker;

    public Action<ItemList.ItemListSelectedEventArgs>? OnSpritePicked;
    public Action<ItemList.ItemListSelectedEventArgs>? OnColorPicked;
    public Action<Color>? OnCustomColorPicked;
    public Action<ItemList.ItemListSelectedEventArgs>? OnWallModePicked;
    public Action<ItemList.ItemListSelectedEventArgs>? OnAirlockModePicked;
    public Dictionary<string, int> ItemColorIndex = new();

    private Dictionary<string, Color> currentPalette = new();
    private const string colorLocKeyPrefix = "spray-painter-color-";
    private List<SprayPainterEntry> CurrentEntries = new List<SprayPainterEntry>();
    private bool _updatingCustomColor;

    public SprayPainterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _emberProceduralIcons = _sysMan.GetEntitySystem<EmberProceduralIconSystem>();
        _colorEntryTexture = _resourceCache.GetResource<TextureResource>("/Textures/Interface/Nano/button.svg.96dpi.png").Texture;

        ModeTabs.SetTabTitle(0, Loc.GetString("spray-painter-tab-airlocks"));
        ModeTabs.SetTabTitle(1, Loc.GetString("spray-painter-tab-walls"));
        ModeTabs.SetTabTitle(2, Loc.GetString("spray-painter-tab-pipes"));
        PopulateAirlockActions();
        PopulateWallActions();
        PaletteButton.OnPressed += _ => TogglePalettePicker();

        CustomColorPicker.OnColorChanged += color =>
        {
            if (_updatingCustomColor)
                return;

            SelectColor(null, true);
            OnCustomColorPicked?.Invoke(color.WithAlpha(1f));
        };
    }

    private static string GetColorLocString(string? colorKey)
    {
        if (string.IsNullOrEmpty(colorKey))
            return Loc.GetString("pipe-painter-no-color-selected");
        var locKey = colorLocKeyPrefix + colorKey;

        if (!Loc.TryGetString(locKey, out var locString))
            locString = colorKey;

        return locString;
    }

    public string? IndexToColorKey(int index)
    {
        return (string?) ColorList[index].Metadata;
    }

    public SprayPainterWallMode IndexToWallMode(int index)
    {
        return (SprayPainterWallMode) WallActionList[index].Metadata!;
    }

    public void Populate(
        List<SprayPainterEntry> entries,
        int selectedStyle,
        SprayPainterWallMode selectedWallMode,
        SprayPainterAirlockMode selectedAirlockMode,
        string? selectedColorKey,
        bool pickedCustomColor,
        Color customColor,
        Dictionary<string, Color> palette)
    {
        // Only clear if the entries change. Otherwise the list would "jump" after selecting an item
        if (!CurrentEntries.Equals(entries))
        {
            CurrentEntries = entries;
            SpriteList.Clear();
            foreach (var entry in entries)
            {
                SpriteList.AddItem(entry.Name, ResolveEntryIcon(entry));
            }
        }

        if (!currentPalette.Equals(palette))
        {
            currentPalette = palette;
            ItemColorIndex.Clear();
            ColorList.Clear();

            foreach (var color in palette)
            {
                var locString = GetColorLocString(color.Key);
                var item = ColorList.AddItem(locString, _colorEntryTexture);
                item.IconModulate = color.Value;
                item.Metadata = color.Key;

                ItemColorIndex.Add(color.Key, ColorList.IndexOf(item));
            }
        }

        // Disable event so we don't send a new event for pre-selectedStyle entry and end up in a loop

        _updatingCustomColor = true;
        CustomColorPicker.Color = customColor.WithAlpha(1f);
        _updatingCustomColor = false;

        SelectColor(selectedColorKey, pickedCustomColor);

        SpriteList.OnItemSelected -= OnSpritePicked;
        SpriteList[selectedStyle].Selected = true;
        SpriteList.OnItemSelected += OnSpritePicked;

        AirlockActionList.OnItemSelected -= OnAirlockModePicked;
        SelectAirlockMode(selectedAirlockMode);
        AirlockActionList.OnItemSelected += OnAirlockModePicked;

        WallActionList.OnItemSelected -= OnWallModePicked;
        SelectWallMode(selectedWallMode);
        WallActionList.OnItemSelected += OnWallModePicked;
    }

    public SprayPainterAirlockMode IndexToAirlockMode(int index)
    {
        return (SprayPainterAirlockMode) AirlockActionList[index].Metadata!;
    }

    private void PopulateAirlockActions()
    {
        AirlockActionList.Clear();
        AddAirlockAction(SprayPainterAirlockMode.ApplyStyle, "spray-painter-airlock-mode-apply-style");
        AddAirlockAction(SprayPainterAirlockMode.PaintDoor, "spray-painter-airlock-mode-paint-door");
        AddAirlockAction(SprayPainterAirlockMode.ClearDoor, "spray-painter-airlock-mode-clear-door");
        AddAirlockAction(SprayPainterAirlockMode.PaintStripe, "spray-painter-airlock-mode-paint-stripe");
        AddAirlockAction(SprayPainterAirlockMode.ClearStripe, "spray-painter-airlock-mode-clear-stripe");
        AddAirlockAction(SprayPainterAirlockMode.PaintWindow, "spray-painter-airlock-mode-paint-window");
        AddAirlockAction(SprayPainterAirlockMode.ClearWindow, "spray-painter-airlock-mode-clear-window");
    }

    private void AddAirlockAction(SprayPainterAirlockMode mode, string locKey)
    {
        AirlockActionList.AddItem(Loc.GetString(locKey), metadata: mode);
    }

    private void PopulateWallActions()
    {
        WallActionList.Clear();
        AddWallAction(SprayPainterWallMode.PaintWall, "spray-painter-wall-mode-paint-wall");
        AddWallAction(SprayPainterWallMode.ClearWallPaint, "spray-painter-wall-mode-clear-wall-paint");
        AddWallAction(SprayPainterWallMode.PaintStripe, "spray-painter-wall-mode-paint-stripe");
        AddWallAction(SprayPainterWallMode.ClearStripe, "spray-painter-wall-mode-clear-stripe");
    }

    private void AddWallAction(SprayPainterWallMode mode, string locKey)
    {
        WallActionList.AddItem(Loc.GetString(locKey), metadata: mode);
    }

    private Texture? ResolveEntryIcon(SprayPainterEntry entry)
    {
        if (entry.PreviewPrototype != null &&
            _emberProceduralIcons.TryGetPrototypeIcon(entry.PreviewPrototype, out var texture))
        {
            return texture;
        }

        return entry.Icon;
    }

    private void SelectWallMode(SprayPainterWallMode mode)
    {
        for (var i = 0; i < WallActionList.Count; i++)
        {
            if (WallActionList[i].Metadata is SprayPainterWallMode itemMode)
                WallActionList[i].Selected = itemMode == mode;
        }
    }

    private void SelectAirlockMode(SprayPainterAirlockMode mode)
    {
        for (var i = 0; i < AirlockActionList.Count; i++)
        {
            if (AirlockActionList[i].Metadata is SprayPainterAirlockMode itemMode)
                AirlockActionList[i].Selected = itemMode == mode;
        }
    }

    private void SelectColor(string? colorKey, bool pickedCustomColor)
    {
        ColorList.OnItemSelected -= OnColorPicked;
        for (var i = 0; i < ColorList.Count; i++)
        {
            ColorList[i].Selected = !pickedCustomColor &&
                colorKey != null &&
                ColorList[i].Metadata is string itemKey &&
                itemKey == colorKey;
        }

        ColorList.OnItemSelected += OnColorPicked;
    }

    private void TogglePalettePicker()
    {
        if (_palettePicker == null)
        {
            _palettePicker = new PaletteColorPicker();
            _palettePicker.OpenToLeft();
            _palettePicker.PaletteList.OnItemSelected += args =>
            {
                if (args.ItemList.GetSelected().FirstOrDefault()?.Metadata is Color color)
                {
                    SetCustomColor(color);
                    OnCustomColorPicked?.Invoke(color.WithAlpha(1f));
                }
            };

            return;
        }

        if (_palettePicker.IsOpen)
            _palettePicker.Close();
        else
            _palettePicker.Open();
    }

    private void SetCustomColor(Color color)
    {
        _updatingCustomColor = true;
        CustomColorPicker.Color = color.WithAlpha(1f);
        _updatingCustomColor = false;
        SelectColor(null, true);
    }
}
