using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

/// A generic locking selector
[GenerateTypedNameReferences]
public sealed partial class RequirementsSelector : BoxContainer
{
    private readonly RadioOptions<int> _options;
    private readonly StripeBack _lockStripe;
    private List<ProtoId<GuideEntryPrototype>>? _guides;

    // Ember: for a job held under more than one name, the name itself becomes the control.
    private OptionButton? _titleOptions;

    public event Action<int>? OnSelected;
    public event Action<List<ProtoId<GuideEntryPrototype>>>? OnOpenGuidebook;

    /// Ember: index into the list passed to <see cref="SetupTitles"/>.
    public event Action<int>? OnTitleSelected;

    public int Selected => _options.SelectedId;


    public RequirementsSelector()
    {
        RobustXamlLoader.Load(this);
        _options = new RadioOptions<int>(RadioOptionsLayout.Horizontal)
        {
            FirstButtonStyle = StyleBase.ButtonOpenRight,
            ButtonStyle = StyleBase.ButtonOpenBoth,
            LastButtonStyle = StyleBase.ButtonOpenLeft,
            HorizontalExpand = true,
        };

        //Override default radio option button width
        _options.GenerateItem = GenerateButton;

        _options.OnItemSelected += args =>
        {
            _options.Select(args.Id);
            OnSelected?.Invoke(args.Id);
        };


        var requirementsLabel = new Label
        {
            Text = Loc.GetString("role-timer-locked"),
            Visible = true,
            HorizontalAlignment = HAlignment.Center,
            StyleClasses = {StyleBase.StyleClassLabelSubText},
        };

        _lockStripe = new StripeBack
        {
            Visible = false,
            HorizontalExpand = true,
            HasMargins = false,
            MouseFilter = MouseFilterMode.Stop,
            Children =
            {
                requirementsLabel,
            },
        };

        Help.OnPressed += _ =>
        {
            if (_guides != null)
                OnOpenGuidebook?.Invoke(_guides);
        };
    }

    /// Actually adds the controls.
    /// </summary>
    public void Setup(
        (string, int)[] items,
        string title,
        int titleSize,
        string? description,
        TextureRect? icon = null,
        List<ProtoId<GuideEntryPrototype>>? guides = null)
    {
        foreach (var (text, value) in items)
            _options.AddItem(Loc.GetString(text), value);

        Help.Visible = guides != null;
        _guides = guides;

        TitleLabel.Text = title;
        TitleLabel.MinSize = new Vector2(titleSize, 0f);
        TitleLabel.ToolTip = description;

        if (icon != null)
        {
            AddChild(icon);
            icon.SetPositionFirst();
        }

        OptionsContainer.AddChild(_options);
        OptionsContainer.AddChild(_lockStripe);
    }

    /// <summary>
    /// Ember: turns the row's name into a dropdown over <paramref name="titles"/>.
    /// </summary>
    /// <remarks>
    /// Replacing the label rather than sitting beside it, because a job with several names does
    /// not have a name plus a setting — the name <em>is</em> the choice, and a second control off
    /// to the side reads as an unrelated option someone forgot to explain.
    ///
    /// Deliberately outside <see cref="_options"/>, so it survives
    /// <see cref="LockRequirements"/>. A name may be what locked the row — the surgeon a doctor
    /// cannot be — and a player who cannot change it back is stuck looking at the reason.
    ///
    /// Call after <see cref="Setup"/>: it takes the label's place and its width.
    /// </remarks>
    public void SetupTitles(IReadOnlyList<(string Name, string? Description)> titles, int selected)
    {
        if (titles.Count == 0)
            return;

        _titleOptions = new OptionButton
        {
            MinSize = TitleLabel.MinSize,
            VerticalAlignment = VAlignment.Center,
            Margin = TitleLabel.Margin,
        };

        for (var i = 0; i < titles.Count; i++)
        {
            _titleOptions.AddItem(titles[i].Name, i);
        }

        _titleOptions.OnItemSelected += args =>
        {
            _titleOptions.SelectId(args.Id);
            _titleOptions.ToolTip = titles[args.Id].Description;
            OnTitleSelected?.Invoke(args.Id);
        };

        var clamped = selected >= 0 && selected < titles.Count ? selected : 0;
        _titleOptions.SelectId(clamped);
        _titleOptions.ToolTip = titles[clamped].Description;

        AddChild(_titleOptions);
        _titleOptions.SetPositionInParent(TitleLabel.GetPositionInParent() + 1);
        TitleLabel.Visible = false;
    }

    public void LockRequirements(FormattedMessage requirements)
    {
        var tooltip = new Tooltip();
        tooltip.SetMessage(requirements);
        _lockStripe.TooltipSupplier = _ => tooltip;
        _lockStripe.Visible = true;
        _options.Visible = false;
    }

    public void UnlockRequirements()
    {
        _lockStripe.Visible = false;
        _options.Visible = true;
    }

    private Button GenerateButton(string text, int value)
    {
        return new Button
        {
            Text = text,
            MinWidth = 90,
            HorizontalExpand = true,
        };
    }

    public void Select(int id)
    {
        _options.Select(id);
    }
}
