using System.Linq;
using System.Numerics;
using Content.Client.Ember.Lobby;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

/// A generic locking selector
[GenerateTypedNameReferences]
public sealed partial class RequirementsSelector : BoxContainer
{
    private readonly RadioOptions<int> _options;
    private readonly StripeBack _lockStripe;
    private List<ProtoId<GuideEntryPrototype>>? _guides;

    // Ember: for a job held under more than one name, the name itself becomes the control.
    private OptionButton? _titleOptions;

    // Ember: the compact form of the same choice - see EmberPriorityBar. Present instead of
    // _options, never beside it.
    private EmberPriorityBar? _priorityBar;

    public event Action<int>? OnSelected;
    public event Action<List<ProtoId<GuideEntryPrototype>>>? OnOpenGuidebook;

    /// Ember: index into the list passed to <see cref="SetupTitles"/>.
    public event Action<int>? OnTitleSelected;

    public int Selected => _priorityBar?.Selected ?? _options.SelectedId;


    public RequirementsSelector()
    {
        RobustXamlLoader.Load(this);
        _options = new RadioOptions<int>(RadioOptionsLayout.Horizontal)
        {
            FirstButtonStyle = StyleBase.ButtonOpenRight,
            ButtonStyle = StyleBase.ButtonOpenBoth,
            LastButtonStyle = StyleBase.ButtonOpenLeft,
            HorizontalExpand = true,
        };

        //Override default radio option button width
        _options.GenerateItem = GenerateButton;

        _options.OnItemSelected += args =>
        {
            _options.Select(args.Id);
            OnSelected?.Invoke(args.Id);
        };


        // Ember: clipped, and the string it carries was shortened to one word. It shares its slot
        // with the priority bar, which is now 192 pixels wide, and "Заблокировано (наведитесь для
        // деталей)" is 230 - an instruction to hover that was itself cut off before the word
        // "details". The reason for the lock is on the tooltip either way.
        var requirementsLabel = new Label
        {
            Text = Loc.GetString("role-timer-locked"),
            Visible = true,
            // ClipText and a minimum together: clipping alone makes the label ask for nothing,
            // and a centred label given nothing draws nothing - the stripe went blank. The
            // minimum is the word itself; the clip is the promise that it will never ask for more.
            ClipText = true,
            MinWidth = 130,
            HorizontalAlignment = HAlignment.Center,
            StyleClasses = {StyleBase.StyleClassLabelSubText},
        };

        _lockStripe = new StripeBack
        {
            Visible = false,
            HorizontalExpand = true,
            HasMargins = false,
            MouseFilter = MouseFilterMode.Stop,
            Children =
            {
                requirementsLabel,
            },
        };

        Help.OnPressed += _ =>
        {
            if (_guides != null)
                OnOpenGuidebook?.Invoke(_guides);
        };
    }

    /// Actually adds the controls.
    /// </summary>
    /// <param name="compact">
    /// Ember: draws the choice as a bar of cells rather than a row of named buttons. For an
    /// ordered preference in a long list, where the names cost more room than they are worth.
    /// </param>
    public void Setup(
        (string, int)[] items,
        string title,
        int titleSize,
        string? description,
        TextureRect? icon = null,
        List<ProtoId<GuideEntryPrototype>>? guides = null,
        bool compact = false)
    {
        if (compact)
        {
            _priorityBar = new EmberPriorityBar(
                items.Select(item => (Loc.GetString(item.Item1), item.Item2)).ToList());
            _priorityBar.OnSelected += value => OnSelected?.Invoke(value);
            OptionsContainer.SetWidth = EmberPriorityBar.WidthFor(items.Length);
        }
        else
        {
            foreach (var (text, value) in items)
                _options.AddItem(Loc.GetString(text), value);
        }

        Help.Visible = guides != null;
        _guides = guides;

        TitleLabel.Text = title;
        TitleLabel.MinSize = new Vector2(titleSize, 0f);
        // Ember: the name goes in the tooltip too. The row is clipped so that one long post
        // cannot set the width of all forty-four, which means the longest names genuinely do not
        // fit - and a name you cannot read in full is worse than a description you have to hover
        // for. Hovering now answers both.
        TitleLabel.ToolTip = description == null ? title : $"{title}\n{description}";

        if (icon != null)
        {
            AddChild(icon);
            icon.SetPositionFirst();
        }

        OptionsContainer.AddChild((Control?) _priorityBar ?? _options);
        OptionsContainer.AddChild(_lockStripe);
    }

    /// <summary>
    /// Ember: turns the row's name into a dropdown over <paramref name="titles"/>.
    /// </summary>
    /// <remarks>
    /// Replacing the label rather than sitting beside it, because a job with several names does
    /// not have a name plus a setting — the name <em>is</em> the choice, and a second control off
    /// to the side reads as an unrelated option someone forgot to explain.
    ///
    /// Deliberately outside <see cref="_options"/>, so it survives
    /// <see cref="LockRequirements"/>. A name may be what locked the row — the surgeon a doctor
    /// cannot be — and a player who cannot change it back is stuck looking at the reason.
    ///
    /// Call after <see cref="Setup"/>: it takes the label's place and its width.
    /// </remarks>
    public void SetupTitles(IReadOnlyList<(string Name, string? Description)> titles, int selected)
    {
        if (titles.Count == 0)
            return;

        _titleOptions = new OptionButton
        {
            MinSize = TitleLabel.MinSize,
            HorizontalExpand = true, // Ember: takes the label's place, and the label expands.
            VerticalAlignment = VAlignment.Center,
            Margin = TitleLabel.Margin,
        };

        for (var i = 0; i < titles.Count; i++)
        {
            _titleOptions.AddItem(titles[i].Name, i);
        }

        _titleOptions.OnItemSelected += args =>
        {
            _titleOptions.SelectId(args.Id);
            _titleOptions.ToolTip = titles[args.Id].Description;
            OnTitleSelected?.Invoke(args.Id);
        };

        var clamped = selected >= 0 && selected < titles.Count ? selected : 0;
        _titleOptions.SelectId(clamped);
        _titleOptions.ToolTip = titles[clamped].Description;

        AddChild(_titleOptions);
        _titleOptions.SetPositionInParent(TitleLabel.GetPositionInParent() + 1);
        TitleLabel.Visible = false;
    }

    public void LockRequirements(FormattedMessage requirements)
    {
        var tooltip = new Tooltip();
        tooltip.SetMessage(requirements);
        _lockStripe.TooltipSupplier = _ => tooltip;
        _lockStripe.Visible = true;
        OptionsControl.Visible = false;
    }

    public void UnlockRequirements()
    {
        _lockStripe.Visible = false;
        OptionsControl.Visible = true;
    }

    private Button GenerateButton(string text, int value)
    {
        return new Button
        {
            Text = text,
            MinWidth = 90,
            HorizontalExpand = true,
        };
    }

    public void Select(int id)
    {
        if (_priorityBar != null)
            _priorityBar.Select(id);
        else
            _options.Select(id);
    }

    /// Ember: whichever of the two forms this row was set up with.
    private Control OptionsControl => (Control?) _priorityBar ?? _options;
}
