using System.Linq;
using Content.Shared.Ember.Medical.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Ember.Medical.Targeting.Widgets;

[GenerateTypedNameReferences]
public sealed partial class EmberTargetingControl : UIWidget
{
    private readonly EmberTargetingUIController _controller;
    private readonly Dictionary<EmberTargetBodyPart, TextureButton> _bodyPartControls;

    public EmberTargetingControl()
    {
        RobustXamlLoader.Load(this);
        _controller = UserInterfaceManager.GetUIController<EmberTargetingUIController>();

        _bodyPartControls = new Dictionary<EmberTargetBodyPart, TextureButton>
        {
            // TODO: ADD EYE AND MOUTH TARGETING
            { EmberTargetBodyPart.Head, HeadButton },
            { EmberTargetBodyPart.Torso, ChestButton },
            { EmberTargetBodyPart.Groin, GroinButton },
            { EmberTargetBodyPart.LeftArm, LeftArmButton },
            { EmberTargetBodyPart.LeftHand, LeftHandButton },
            { EmberTargetBodyPart.RightArm, RightArmButton },
            { EmberTargetBodyPart.RightHand, RightHandButton },
            { EmberTargetBodyPart.LeftLeg, LeftLegButton },
            { EmberTargetBodyPart.LeftFoot, LeftFootButton },
            { EmberTargetBodyPart.RightLeg, RightLegButton },
            { EmberTargetBodyPart.RightFoot, RightFootButton },
        };

        foreach (var bodyPartButton in _bodyPartControls)
        {
            bodyPartButton.Value.MouseFilter = MouseFilterMode.Stop;
            bodyPartButton.Value.OnPressed += _ => SetActiveBodyPart(bodyPartButton.Key);

            TargetDoll.Texture = Theme.ResolveTexture("target_doll");
        }
    }

    private void SetActiveBodyPart(EmberTargetBodyPart bodyPart) => _controller.CycleTarget(bodyPart);

    public void SetBodyPartsVisible(EmberTargetBodyPart bodyPart)
    {
        foreach (var bodyPartButton in _bodyPartControls)
            bodyPartButton.Value.Children.First().Visible = bodyPartButton.Key == bodyPart;
    }

    protected override void OnThemeUpdated() => TargetDoll.Texture = Theme.ResolveTexture("target_doll");

    public void SetTargetDollVisible(bool visible) => Visible = visible;

}
