using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Ember.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class EmberSurgeryWindow : DefaultWindow
{
    public EmberSurgeryWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
