using Content.Client.Ember.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Ember.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class EmberSurgeryStepButton : EmberChoiceControl
{
    public EntityUid Step { get; set; }

    public EmberSurgeryStepButton()
    {
        RobustXamlLoader.Load(this);
    }
}
