using System.Linq;
using Content.Client.Stylesheets;
using Content.Shared.Decals;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization.Markdown.Value;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.Decals.UI;

[GenerateTypedNameReferences]
public sealed partial class DecalPlacerWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _e = default!;

    private readonly DecalPlacementSystem _decalPlacementSystem;

    public FloatSpinBox RotationSpinBox;

    private PaletteColorPicker? _picker;

    private SortedDictionary<string, Texture>? _decals;

    /// <summary>Which category each decal belongs to, so the list can be narrowed to one of them.</summary>
    private readonly Dictionary<string, string> _categoryOf = new();

    private readonly List<string> _categories = new();
    private string? _category;
    private string? _selected;
    private Color _color = Color.White;
    private bool _useColor;
    private bool _snap;
    private float _rotation;
    private bool _cleanable;
    private int _zIndex;

    private bool _auto;

    /// <summary>Gives up rather than looping forever if a prototype somehow inherits from itself.</summary>
    private const int MaximumDepth = 16;

    public DecalPlacerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _decalPlacementSystem = _e.System<DecalPlacementSystem>();

        // This needs to be done in C# so we can have custom stuff passed in the constructor
        // and thus have a proper step size
        RotationSpinBox = new FloatSpinBox(90.0f, 0)
        {
            HorizontalExpand = true
        };
        SpinBoxContainer.AddChild(RotationSpinBox);

        Search.OnTextChanged += _ => RefreshList();
        Category.OnItemSelected += args =>
        {
            Category.SelectId(args.Id);
            _category = args.Id == 0 ? null : _categories[args.Id - 1];
            RefreshList();
        };

        // Most decals are drawn facing one way and turned to suit, and reaching for a number every time is a
        // poor way to say "the other way up". The spin box is still there for anything that needs an odd angle.
        FaceSouth.OnPressed += _ => SetRotation(0f);
        FaceEast.OnPressed += _ => SetRotation(90f);
        FaceNorth.OnPressed += _ => SetRotation(180f);
        FaceWest.OnPressed += _ => SetRotation(270f);
        ColorPicker.OnColorChanged += OnColorPicked;

        PickerOpen.OnPressed += _ =>
        {
            if (_picker is null)
            {
                _picker = new PaletteColorPicker();
                _picker.OpenToLeft();
                _picker.PaletteList.OnItemSelected += args =>
                {
                    var color = (args.ItemList.GetSelected().First().Metadata as Color?)!.Value;
                    ColorPicker.Color = color;
                    OnColorPicked(color);
                };
            }
            else
            {
                if (_picker.IsOpen)
                {
                    _picker.Close();
                }
                else
                {
                    _picker.Open();
                }
            }
        };

        RotationSpinBox.OnValueChanged += args =>
        {
            _rotation = args.Value;
            UpdateDecalPlacementInfo();
        };
        EnableAuto.OnToggled += args =>
        {
            _auto = args.Pressed;
            if (_selected != null)
                SelectDecal(_selected);
        };
        EnableColor.OnToggled += args =>
        {
            _useColor = args.Pressed;
            UpdateDecalPlacementInfo();
            RefreshList();
        };
        EnableSnap.OnToggled += args =>
        {
            _snap = args.Pressed;
            UpdateDecalPlacementInfo();
        };
        EnableCleanable.OnToggled += args =>
        {
            _cleanable = args.Pressed;
            UpdateDecalPlacementInfo();
        };
        ZIndexSpinBox.ValueChanged += args =>
        {
            _zIndex = args.Value;
            UpdateDecalPlacementInfo();
        };
    }

    private void SetRotation(float degrees)
    {
        _rotation = degrees;
        RotationSpinBox.Value = degrees;
        UpdateDecalPlacementInfo();
    }

    private void OnColorPicked(Color color)
    {
        _color = color;
        UpdateDecalPlacementInfo();
        RefreshList();
    }

    private void UpdateDecalPlacementInfo()
    {
        if (_selected is null)
            return;

        var color = _useColor ? _color : Color.White;
        _decalPlacementSystem.UpdateDecalInfo(_selected, color, _rotation, _snap, _zIndex, _cleanable);
    }

    private void RefreshList()
    {
        // Clear
        Grid.RemoveAllChildren();
        if (_decals == null)
            return;

        var filter = Search.Text.ToLowerInvariant();
        foreach (var (decal, tex) in _decals)
        {
            if (!decal.ToLowerInvariant().Contains(filter))
                continue;

            if (_category != null && (!_categoryOf.TryGetValue(decal, out var category) || category != _category))
                continue;

            var button = new TextureButton
            {
                TextureNormal = tex,
                Name = decal,
                ToolTip = decal,
                Modulate = _useColor ? _color : Color.White
            };
            button.OnPressed += ButtonOnPressed;
            if (_selected == decal)
            {
                var panelContainer = new PanelContainer
                {
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = StyleNano.ButtonColorDefault
                    },
                    Children =
                    {
                        button
                    }
                };
                Grid.AddChild(panelContainer);
            }
            else
                Grid.AddChild(button);
        }
    }

    private void ButtonOnPressed(ButtonEventArgs obj)
    {
        if (obj.Button.Name == null)
            return;

        SelectDecal(obj.Button.Name);
    }

    private void SelectDecal(string decalId)
    {
        if (!_prototype.TryIndex<DecalPrototype>(decalId, out var decal))
            return;

        _selected = decalId;

        if (_auto)
        {
            EnableCleanable.Pressed = decal.DefaultCleanable;
            EnableColor.Pressed = decal.DefaultCustomColor;
            EnableSnap.Pressed = decal.DefaultSnap;
            _cleanable = decal.DefaultCleanable;
            _useColor = decal.DefaultCustomColor;
            _snap = decal.DefaultSnap;
        }
        SelectedLabel.Text = decalId;
        UpdateDecalPlacementInfo();
        RefreshList();
    }

    public void Populate(IEnumerable<DecalPrototype> prototypes)
    {
        _decals = new SortedDictionary<string, Texture>();
        _categoryOf.Clear();
        _categories.Clear();

        foreach (var decalPrototype in prototypes)
        {
            if (!decalPrototype.ShowMenu)
                continue;

            _decals.Add(decalPrototype.ID, decalPrototype.Sprite.Frame0());

            if (RootOf(decalPrototype.ID) is { } category)
                _categoryOf[decalPrototype.ID] = category;
        }

        _categories.AddRange(_categoryOf.Values.Distinct().OrderBy(CategoryName));

        Category.Clear();
        Category.AddItem(Loc.GetString("decal-placer-window-category-all"), 0);
        for (var i = 0; i < _categories.Count; i++)
        {
            Category.AddItem(CategoryName(_categories[i]), i + 1);
        }

        Category.SelectId(_category == null ? 0 : _categories.IndexOf(_category) + 1);
        RefreshList();
    }

    /// <summary>
    /// The outermost prototype a decal inherits from, which is what its category is: decals are grouped by
    /// inheritance, the same way the mapping window groups them.
    /// </summary>
    /// <remarks>
    /// Walked through the raw prototype data rather than through indexed prototypes, because the ancestors are
    /// abstract and only exist as YAML.
    /// </remarks>
    private string? RootOf(string id)
    {
        string? root = null;

        for (var depth = 0; depth < MaximumDepth; depth++)
        {
            if (!_prototype.TryGetMapping(typeof(DecalPrototype), id, out var node) ||
                !node.TryGet("parent", out ValueDataNode? parent))
            {
                return root;
            }

            root = id = parent.Value;
        }

        return root;
    }

    private string CategoryName(string id)
    {
        return Loc.TryGetString($"decal-category-{id.ToLowerInvariant()}", out var name) ? name : id;
    }

    protected override void Opened()
    {
        base.Opened();
        _decalPlacementSystem.SetActive(true);
    }

    public override void Close()
    {
        base.Close();
        _decalPlacementSystem.SetActive(false);
    }
}
