using System.Linq;
using Content.Client.Stylesheets;
using Content.Shared.Maps;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Placement;
using Robust.Client.Placement.Modes;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization.Markdown.Value;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.Ember.Tiles;

/// <summary>
/// The sandbox tile picker, laid out like the decal placer rather than as a list of names.
/// </summary>
/// <remarks>
/// The engine's own window is a flat <see cref="ItemList"/>, which was fine while tiles were a few dozen
/// hand-drawn floors. A floor per material turns that into hundreds of rows, most of them sharing a mask and
/// telling themselves apart by colour alone, so this one groups them the way the mapping window does -- by
/// inheritance -- and draws each one in its own colour.
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class EmberTileSpawnWindow : DefaultWindow
{
    [Dependency] private readonly IPlacementManager _placement = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IResourceCache _resources = default!;

    /// <summary>Gives up rather than looping forever if a prototype somehow inherits from itself.</summary>
    private const int MaximumDepth = 16;

    private readonly Dictionary<string, string> _categoryOf = new();
    private readonly List<string> _categories = new();
    private readonly List<ContentTileDefinition> _shown = new();

    private string? _category;
    private string? _selected;

    public EmberTileSpawnWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Search.OnTextChanged += _ => Refresh();
        Category.OnItemSelected += args =>
        {
            Category.SelectId(args.Id);
            // Id 0 is every tile and the last id is the uncategorised pile; neither indexes the list.
            _category = args.Id == 0 || args.Id > _categories.Count ? null : _categories[args.Id - 1];
            Refresh();
        };

        MirrorButton.OnToggled += OnMirrorToggled;
        EraseButton.OnToggled += OnEraseToggled;

        _placement.PlacementChanged += OnPlacementChanged;
        _placement.DirectionChanged += (_, _) => UpdateRotation();
        _placement.MirroredChanged += (_, _) => MirrorButton.Pressed = _placement.Mirrored;

        Reload();
        UpdateRotation();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing)
            return;

        _placement.PlacementChanged -= OnPlacementChanged;
    }

    private void Reload()
    {
        _categoryOf.Clear();
        _categories.Clear();

        foreach (var tile in _prototype.EnumeratePrototypes<ContentTileDefinition>())
        {
            if (((ITileDefinition) tile).EditorHidden || tile.Sprite == null)
                continue;

            if (RootOf(tile.ID) is { } category)
                _categoryOf[tile.ID] = category;
        }

        _categories.AddRange(_categoryOf.Values.Distinct().OrderBy(CategoryName));

        Category.Clear();
        Category.AddItem(Loc.GetString("ember-tile-spawn-window-category-all"), 0);

        for (var i = 0; i < _categories.Count; i++)
        {
            Category.AddItem(CategoryName(_categories[i]), i + 1);
        }

        // Tiles that inherit from nothing -- which is every tile we did not write -- would otherwise be
        // unreachable once a category is picked.
        Category.AddItem(Loc.GetString("ember-tile-spawn-window-category-other"), _categories.Count + 1);

        Category.SelectId(0);
        Refresh();
    }

    private void Refresh()
    {
        Grid.RemoveAllChildren();
        _shown.Clear();

        var filter = Search.Text.Trim();
        var other = _categories.Count + 1;

        foreach (var tile in _prototype.EnumeratePrototypes<ContentTileDefinition>()
                     .Where(t => !((ITileDefinition) t).EditorHidden && t.Sprite != null)
                     .OrderBy(t => Loc.GetString(t.Name)))
        {
            var name = Loc.GetString(tile.Name);

            if (filter.Length > 0 &&
                !name.Contains(filter, StringComparison.CurrentCultureIgnoreCase) &&
                !tile.ID.Contains(filter, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var known = _categoryOf.TryGetValue(tile.ID, out var category);

            if (_category != null && (!known || category != _category))
                continue;

            if (Category.SelectedId == other && known)
                continue;

            _shown.Add(tile);
            Grid.AddChild(Button(tile, name));
        }
    }

    private Control Button(ContentTileDefinition tile, string name)
    {
        var sheet = _resources.GetResource<TextureResource>(tile.Sprite!.Value.ToString()).Texture;

        // A tile's texture is its variants laid out in a strip, so drawing the whole thing stretches the
        // random ones across the cell. Only the first variant is the tile's own face.
        var texture = sheet.Width > sheet.Height
            ? new AtlasTexture(sheet, UIBox2.FromDimensions(0, 0, sheet.Height, sheet.Height))
            : sheet;

        var button = new TextureButton
        {
            TextureNormal = texture,
            Name = tile.ID,
            ToolTip = name,
            // The sprite is a mask shared by a whole family; without this a dozen metals are one grey square.
            Modulate = tile.Color,
        };

        button.OnPressed += _ => Select(tile, name);

        if (_selected != tile.ID)
            return button;

        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = StyleNano.ButtonColorDefault },
            Children = { button },
        };
    }

    private void Select(ContentTileDefinition tile, string name)
    {
        _selected = tile.ID;
        SelectedLabel.Text = name;
        EraseButton.Pressed = false;

        _placement.BeginPlacing(new PlacementInformation
        {
            PlacementOption = nameof(AlignTileAny),
            TileType = tile.TileId,
            Range = 400,
            IsTile = true,
        });

        MirrorButton.Disabled = !((ITileDefinition) tile).AllowRotationMirror;
        Refresh();
    }

    private void OnEraseToggled(ButtonToggledEventArgs args)
    {
        _placement.Clear();

        if (!args.Pressed)
            return;

        _placement.BeginPlacing(new PlacementInformation
        {
            PlacementOption = nameof(AlignTileAny),
            TileType = 0,
            Range = 400,
            IsTile = true,
        });
    }

    private void OnMirrorToggled(ButtonToggledEventArgs args)
    {
        _placement.Mirrored = args.Pressed;
    }

    private void OnPlacementChanged(object? sender, EventArgs e)
    {
        if (_placement.CurrentPermission is { IsTile: true })
            return;

        _selected = null;
        SelectedLabel.Text = Loc.GetString("ember-tile-spawn-window-nothing-selected");
        EraseButton.Pressed = false;
        Refresh();
    }

    private void UpdateRotation()
    {
        RotationLabel.Text = Loc.GetString("ember-tile-spawn-window-rotation",
            ("direction", _placement.Direction.ToString()));
    }

    /// <summary>The category's own name, read from YAML because the categories are abstract tiles.</summary>
    private string CategoryName(string id)
    {
        if (_prototype.TryGetMapping(typeof(ContentTileDefinition), id, out var node) &&
            node.TryGet("name", out ValueDataNode? name))
        {
            return Loc.GetString(name.Value);
        }

        return id;
    }

    /// <summary>
    /// The outermost tile a definition inherits from, which is what its category is.
    /// </summary>
    /// <remarks>
    /// Walked through the raw prototype data rather than through indexed prototypes, because the ancestors
    /// are abstract and only exist as YAML.
    /// </remarks>
    private string? RootOf(string id)
    {
        string? root = null;

        for (var depth = 0; depth < MaximumDepth; depth++)
        {
            if (!_prototype.TryGetMapping(typeof(ContentTileDefinition), id, out var node) ||
                !node.TryGet("parent", out ValueDataNode? parent))
            {
                return root;
            }

            root = id = parent.Value;
        }

        return root;
    }
}
